# Generated by Django 4.2.6 on 2024-01-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_author_options_rename_first_name_author_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='id',
            new_name='uniqueid',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='imprint',
        ),
        migrations.AddField(
            model_name='book',
            name='imprint',
            field=models.CharField(default='Peregrin', max_length=200),
            preserve_default=False,
        ),
    ]
